### ISSUE TITLE
Set useSsl from appsettings.json

### ISSUE THREAD

**Issue by angroPowel** [serilog-contrib/serilog-sinks-graylog#88]
Hello, is there a way to set useSsl from appsettings.json? 

What I want to achieve: 

![image](https://user-images.githubusercontent.com/69149792/216003228-b9b0fa8e-1001-46a6-802f-486de06e47ec.png)

I know the following work, but I would prefer to have it all in appsettings.json:

![image](https://user-images.githubusercontent.com/69149792/216003097-85decea6-85d6-43fa-845f-da24ec0914a5.png)

Thanks in advance for any reply.

**Comment by augustoproiete** [comment]
Looks like this might have been fixed by PR https://github.com/whir1/serilog-sinks-graylog/pull/83 merged on Sep 19, 2022, but new versions of the [Serilog.Sinks.Graylog](https://www.nuget.org/packages/Serilog.Sinks.Graylog#versions-body-tab) NuGet package have not been released since Dec 29, 2021.

@whir1 Any plans of shipping an updated NuGet package?

**Comment by whir1** [comment]
fixed
